services:

  mongo:
    image: mongo:7
    container_name: rag_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - backend

  postgres:
    image: pgvector/pgvector:pg16
    container_name: docsly_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_MAIN_DATABASE}
    networks:
      - backend

volumes:
  mongodata:
  pgdata:

networks:
  backend:
    driver: bridge
