from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict, Any

class LLMResponse:
    """
    This class standardizes the response from any AI model.
    No matter which model we use, the answer will always look like this.
    """
    def __init__(self, text: str, tokens: Optional[int] = None, metadata: Optional[Dict[str, Any]] = None):
        # The actual text generated by the AI
        self.text = text
        # The number of tokens used (good for calculating costs)
        self.tokens = tokens
        # Any extra information (like the model name)
        self.metadata = metadata if metadata else {}

class BaseLLM(ABC):
    """
    This is the Base Interface for all AI models (like a blueprint).
    Every new AI model we add MUST use this blueprint and have these methods.
    """
    def __init__(self, api_key: Optional[str] = None, api_url: Optional[str] = None, 
                 default_input_max_characters: int = 1000, 
                 default_generation_max_output_tokens: int = 1000, 
                 default_generation_temperature: float = 0.1):
        
        # Save the basic settings for the model
        self.api_key = api_key
        self.api_url = api_url
        self.default_input_max_characters = default_input_max_characters
        self.default_generation_max_output_tokens = default_generation_max_output_tokens
        self.default_generation_temperature = default_generation_temperature

    @abstractmethod
    def generate_text(self, prompt: str, chat_history: list=None, max_output_tokens: Optional[int]=None, temperature: Optional[float] = None) -> LLMResponse:
        """
        Ask the AI a question and get a text answer.
        It requires a prompt (the question) and returns an LLMResponse object.
        """
        pass

    @abstractmethod
    def embed_text(self, text: str, document_type: Optional[str] = None) -> list[float]:
        """
        Convert text into a list of numbers (vectors).
        This is used for searching and RAG (Retrieval-Augmented Generation).
        """
        pass

    @abstractmethod
    def construct_prompt(self, prompt: str, role: str) -> dict:
        """
        Build a dictionary showing who is speaking.
        Example: {"role": "user", "content": "Hello"}
        """
        pass

    def set_generation_model(self, model_id: str):
        """Set the specific model ID to use for generation."""
        self.generation_model_id = model_id

    def set_embedding_model(self, model_id: str):
        """Set the specific model ID to use for embeddings."""
        self.embedding_model_id = model_id
